### PR TITLE
Create AddCoolingProfile.py

### PR DESCRIPTION
**Pull request by GregValiant**
A post processor that adds fan control "By Layer" or "By Feature.
Up to 4 fan circuits are supported.
RepRap "fan scale 0 to 1" is supported.
There is no conflict with the current cooling settings in Cura.
This has been merged into UM Cura.

It was debugged in Master version 4.20.16

### CODE REVIEW

**Comment by smartavionics** [comment]
OK, it'll be in the next release. Thanks.

**Comment by smartavionics** [comment]
Just a thought... You have given this an MB suffix. Does that mean that a project file that uses this script won't work right if it is loaded into UM Cura (which I assume has a similar script without the MB suffix)?

**Comment by GregValiant** [comment]
No.  I did it to keep track.  Inside it is exactly the same.
GitHub will get confused but I'll change it now.
I think I'll close this PR and open a new one.

**Comment by GregValiant** [comment]
OK.  The name was changed to protect the innocent.

**Comment by smartavionics** [comment]
Hi Greg, I'm contacting you via this old PR because I don't have an email for you and I no longer post on the forum. I just wanted to point out that my Cura provides configurable fan speed on overhangs.

https://community.ultimaker.com/topic/46921-ultimaker-cura-overhanging-wall-cooling/

**Comment by GregValiant** [comment]
If you click on my avatar over there you canMessage sent via the forum.

I had the impression they were looking for something more like "Extra fan for overhangs" rather than simply "Extra fan for First Skin Over Support".
This is from your fork.  The "first skin over support" is receiving extra attention as it should, but the walls are ignored.
The angled surface isn't receiving any attention at all and it is an overhang.
image

**Comment by smartavionics** [comment]
I was actually thinking of these settings...

Screenshot_2025-05-05_21-18-33

**Pull request closed without merging**
