### PR TITLE
Update fdmprinter.def.json.po

### PR DESCRIPTION
**Pull request by 5axes**
Update the French Translation

### CODE REVIEW

**Comment by smartavionics** [comment]
Hi, sorry for the slow response, I've been busy for a few days. Is this PR complete now? If so, I will merge it. Thanks for the contribution.

**Comment by 5axes** [comment]
Yes you can Merge if you think it's valid. By the way I'm Also working on a special SettingsGuide Release based on your release : https://github.com/5axes/CuraMasterSettings 

Note Right now it's just a primary version.

**Comment by smartavionics** [comment]
Hi, you have an extraneous msgstr "" on line 6861.

**Comment by 5axes** [comment]
Yes you're right I'm Using Virtaal for the PO translation and it doesn't give any error !

**Comment by smartavionics** [comment]
OK, I've merged this into my testing branch and it will be in the next release.

**Comment by smartavionics** [comment]
Hi, your latest update still has a problem with an extraneous msgstr ""!
```
#: fdmprinter.def.json
msgctxt "hole_xy_offset_max_size label"
msgid "Hole Horizontal Expansion Max Size"msgstr ""
msgstr "Taille Maxi Expansion horizontale des trous"
```

**Pull request merged**
