### PR TITLE
My additions to your PR

### PR DESCRIPTION
**Pull request by BagelOrb**
Please review which changes you like and merge if you agree with my changes to your PR.

I introduced a new setting min_skin_angle_for_expansion.

I moved settings out of the children of expand_skin_into_infill. Parent settings should only handle exactly the same as all children. If all child settings are changed, the parent becomes disabled, because the parent doesn't do anything more than all the children.

I changed some default values.

I changed the descriptions.

### CODE REVIEW

**Comment by BagelOrb** [comment]
I thought we used the word 'direction' for skin and infill angles.

Indeed the description should say that 0 is horizontal. Or 0 should be vertical and the description should say that.

I introduced the min_skin_angle_for_expansion setting, because I think the Minimum Skin Width for Expansion is a bit weird.
It should have been called the _Maximum_ Skin Angle for Expansion, though, because all angles shallower than the given angle would result in skin wider than the min_skin_angle_for_expansion.
I find the concept of the angle of skin surfaces easier to understand than the skin width.
Also: what's the real reason for limiting skin expansion? Do you only want skin expansion where there are nearly horizontal surfaces, or do you want skin expansion where there is large skin?

I'm not sure whether you find the angle setting more confusing than the min skin width setting, just because you are already familiar with the skin width setting, or whether the angle setting is just a confusing setting.

**Comment by smartavionics** [comment]
The reason for limiting the skin expansion is as follows: imagine a horizontal surface which has a sloping wall that grows above it. When the skin expansion is enabled the skin layers below the wall will be expanded so they go further under the wall than the perimeter lines which is what we want. But on the layers above, because the wall is sloping, there can be narrow areas of skin created that lie next to the wall perimeters that (unless they are shrunk to zero width) will also be expanded but that isn't needed because those narrow skin areas don't extend beyond the wall perimeter (unlike the horizontal skin which the wall sits upon).

I hope that makes sense.

**Comment by BagelOrb** [comment]
Yes I understand why we want it, but your explanation actually captures the reason for including both settings:

> because the wall is sloping

is a reason for including the angle setting

> there can be narrow areas of skin

is a reason for including the skin width setting.

I'm trying to find out what would be the most logical way for a user to think about it,
I think that the angles approach is more geared toward what the user sees, while the skin width approach for more geared toward the workings of the engine.

**Comment by smartavionics** [comment]
This sounds like a use for the shrinking skin feature...

https://ultimaker.com/en/community/39214-feature-add-angle-for-top-bottom-internal-layer-generation

**Comment by BagelOrb** [comment]
Shrinking skin is very much related to your skin expansion feature indeed.

Given that you do understand why you would want an angle setting for skin shrink, I find it hard to understand you are opposed to an angle setting for skin expansion.

**Comment by smartavionics** [comment]
The expansion distance is based on the distance between the infill lines. As we are trying to ensure that the skin reaches all the way across the gap between the infill lines, the default expansion distance is 1.4 times the gap between the infill lines. In practice, the expansion distance can be smaller than that and good results are still obtained. The expansion distance isn't affected by the slope of the wall above the skin (like the shrink distance is).

**Comment by BagelOrb** [comment]
No indeed, the angle setting is used for the limit at which the expansion distance is applied. (The angle setting is not used to determine the expansion, but the minimal width for expansion)
For slopes which are too vertical, the skin will be too narrow and so the expansion won't be applied there.
You can set the maximum angle, which determines the minimal skin width which limits the expansion.

**Comment by smartavionics** [comment]
I'm still not convinced about the need for min_skin_angle_for_expansion but as long as you can also set the min_skin_width_for_expansion setting independently then I don't have a big problem with the changes to the JSON and will incorporate them.

**Comment by BagelOrb** [comment]
I'll also discuss with some colleagues to get a second opinion ;)

**Pull request merged**
